version: "3"
name: inventory-hub-backend

volumes:
  postgres-data:
  azurite-data:

services:
  postgres:
    extends:
      file: compose-base.yml
      service: postgres
    ports:
      - 5432:5432

  azurite:
    extends:
      file: compose-base.yml
      service: azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
