version: "3"
name: inventory-hub-backend

volumes:
  postgres-data:
  azurite-data:

services:
  backend:
    profiles: [server]
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - azurite
    restart: no

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - azurite-data:/data
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    restart: unless-stopped