version: "3"
name: inventory-hub-backend

volumes:
  postgres-data:
  azurite-data:

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER 
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME} 
    ports:
      - 5432:5432
    networks:
      fullstack:
        aliases:
          - postgres
    restart: unless-stopped


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - azurite-data:/data
    healthcheck:
      test: nc 0.0.0.0 10000 -z
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      fullstack:
        aliases:
          - azurite
    restart: unless-stopped
