version: "3"
name: inventory-hub-backend

volumes:
  src:
  postgres-data:
  azurite-data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure 
    depends_on:
      # fullstack-azurite:
        # condition: service_healthy
      fullstack-postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - src:/usr/src/app/
    networks:
      - fullstack

  fullstack-postgres:
    extends:
      file: compose-base.yml
      service: postgres

  fullstack-azurite:
    extends:
      file: compose-base.yml
      service: azurite

networks:
  fullstack:
    driver: bridge
  