version: "3"
name: inventory-hub-backend

volumes:
  postgres-data:
  azurite-data:

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory-hub-db
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - azurite-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
