version: "3"
name: inventory-hub-backend

volumes:
  postgres-data:
  azurite-data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - azurite
    restart: no
    ports:
      - 8000:8000
    env_file: .env

  postgres:
    extends:
      file: compose-base.yml
      service: postgres

  azurite:
    extends:
      file: compose-base.yml
      service: azurite
